### ISSUE TITLE
Install latest R from CRAN?

### ISSUE THREAD

**Issue by ck37** [ucberkeley/bce#31]
Would it be possible to use CRAN's version of R rather than the default one in Ubuntu? I have found that I have to re-install R from CRAN since the current one on BCE is pretty old (3.0.2 rather than ~3.2.0) and has bugs that prevent parallel machine learning in caret from working.

Switching to Ubuntu 15.04 is helpful but still gets us a somewhat old version of R (3.1) - https://launchpad.net/ubuntu/vivid/i386/r-base-core

According to http://askubuntu.com/questions/506560/how-to-install-package-of-r we would need to add a CRAN mirror to the apt packages list that is specific to the Ubuntu version, then that will be used when installing R.

**Comment by paciorek** [comment]
This makes sense to me.  Ryan, how does that sound for summer 2015 version?

**Comment by ryanlovett** [comment]
This has already been committed:
https://github.com/ucberkeley/bce/blob/dev/provisioning/bootstrap.d/70-r

We will use an MRAN snapshot to freeze the version of both R and its packages. The vivid directory hasn't been pulled from the rrutter PPA yet which is why I haven't been able to roll out a summer-preview release.
